version: "3.9"

services:
  # only allow container, service and network info
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_proxy
    environment:
      CONTAINERS: 1      
      SERVICES: 1          
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=false"
      - "--api.insecure=false"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    ports:
      - "80:80"
      - "443:443"
      # - "7070:8080"                         # dashboard
    networks:
      - internal
      - external

networks:
  internal:
  external:
    external: true
