version: "3.9"

services:
  # only allow container, service and network info
  docker-proxy:
    image: tecnativa/docker-socket-proxy
    container_name: docker_proxy
    environment:
      CONTAINERS: 1      
      SERVICES: 1          
      NETWORKS: 1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal

  traefik:
    image: traefik:v3.0
    container_name: traefik
    command:
      - "--api.dashboard=true"
      - "--api.insecure=true"
      - "--providers.docker.endpoint=tcp://docker-proxy:2375"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.file.filename=/etc/traefik/dynamic.yml"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
    ports:
      - "80:80"
      - "443:443"
      - "7070:8080"
    volumes:
      - certs:/certs
      - dynamic-config:/etc/traefik
    networks:
      - internal
      - external
    # create the inline dynamic.yml on startup
    entrypoint: >
      sh -c "echo 'tls:
        certificates:
          - certFile: /certs/traefik.crt
            keyFile: /certs/traefik.key' > /etc/traefik/dynamic.yml &&
        traefik"

volumes:
  certs:
  dynamic-config:

networks:
  internal:
  external:
    external: true
