---
- name: Deploy Portainer repository stacks
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    portainer_url: "https://10.0.100.10:9443"
    portainer_username: "{{ lookup('env', 'portainer_username') }}"
    portainer_password: "{{ lookup('env', 'portainer_password') }}"
    portainer_endpoint_id: "2" # seems to be default
    MYSQL_PASSWORD: "{{ lookup('env', 'portainer_username') }}"
    MYSQL_ROOT_PASSWORD: "{{ lookup('env', 'MYSQL_ROOT_PASSWORD') }}"
    ZBX_SERVER_HOST: "10.0.100.10"
    ZBX_HOSTNAME: "Test Environment"


    # Environment variables for stack
    stack_env_vars:
      - name: MYSQL_DATABASE
        value: "zabbix_proxy"
      - name: MYSQL_USER
        value: "zabbix"
      - name: MYSQL_PASSWORD
        value: "{{ MYSQL_PASSWORD }}"
      - name: MYSQL_ROOT_PASSWORD
        value: "{{ MYSQL_ROOT_PASSWORD }}"
      - name: ZBX_SERVER_HOST
        value: "{{ ZBX_SERVER_HOST }}"
      - name: ZBX_SERVER_PORT
        value: "10051"
      - name: ZBX_HOSTNAME
        value: "{{ ZBX_HOSTNAME }}"
      - name: ZBX_PROXYMODE
        value: "0"
      - name: ZBX_CACHESIZE
        value: "256M"
      - name: ZBX_HISTORYCACHESIZE
        value: "128M"
      - name: ZBX_HISTORYINDEXCACHESIZE
        value: "32M"
      - name: ZBX_STARTPOLLERS
        value: "50"
      - name: ZBX_STARTSNMPPOLLERS
        value: "20"
      - name: ZBX_STARTPREPROCESSORS
        value: "20"
      - name: ZBX_STARTTRAPPERS
        value: "20"
      - name: DB_SERVER_HOST
        value: "mysql"

  tasks:
    - name: Get Portainer auth token
      ansible.builtin.uri:
        url: "{{ portainer_url }}/api/auth"
        method: POST
        body_format: json
        body:
          Username: "{{ portainer_username }}"
          Password: "{{ portainer_password }}"
        validate_certs: no
      register: portainer_auth

    - name: Deploy Zabbix stack with env vars
      ansible.builtin.uri:
        url: "{{ portainer_url }}/api/stacks/create/standalone/repository?endpointId={{ portainer_endpoint_id }}"
        method: POST
        headers:
          Authorization: "Bearer {{ portainer_auth.json.jwt }}"
          Content-Type: "application/json"
        body_format: json
        body:
          Name: "zabbix-proxy"
          repositoryURL: "https://github.com/Myrenic/apps"
          composeFile: "/stacks/zabbix-proxy/docker-compose.yml"
          AutoUpdate:
            Interval: "5m"
          env: "{{ stack_env_vars }}"
        validate_certs: no
      register: new_stack_result
