- name: Deploy Zabbix Server Stack
  hosts: localhost
  connection: local
  gather_facts: false

  vars:
    portainer_url: "https://10.0.100.10:9443"
    portainer_username: "{{ lookup('env', 'portainer_username') }}"
    portainer_password: "{{ lookup('env', 'portainer_password') }}"
    portainer_endpoint_id: "2"
    zbx_server_name: "{{ lookup('env', 'ZBX_SERVER_NAME') }}"
    zbx_node_name: "{{ lookup('env', 'ZBX_NODE_NAME') }}"
    zbx_node_ip: "{{ lookup('env', 'zbx_node_ip') }}"
    zbx_db_password: "{{ lookup('env', 'ZBX_DB_PASSWORD') }}"

    stack_env_vars:
      - name: DB_SERVER_HOST
        value: "zabbix-db"
      - name: ZBX_LOG_LEVEL
        value: "4"
      - name: POSTGRES_DB
        value: "zabbix"
      - name: POSTGRES_USER
        value: "zabbix"
      - name: POSTGRES_PASSWORD
        value: "{{ zbx_db_password }}"
      - name: ZBX_CACHESIZE
        value: "2G"
      - name: ZBX_HISTORYCACHESIZE
        value: "1G"
      - name: ZBX_TRENDCACHESIZE
        value: "512M"
      - name: ZBX_VALUECACHESIZE
        value: "512M"
      - name: ZBX_STARTPOLLERS
        value: "200"
      - name: ZBX_STARTIPMIPOLLERS
        value: "10"
      - name: ZBX_STARTPOLLERSUNREACHABLE
        value: "40"
      - name: ZBX_STARTTRAPPERS
        value: "100"
      - name: ZBX_STARTPINGERS
        value: "40"
      - name: ZBX_STARTVMWARECOLLECTORS
        value: "5"
      - name: ZBX_STARTDISCOVERERS
        value: "30"
      - name: ZBX_STARTHTTPPOLLERS
        value: "30"
      - name: ZBX_STARTTIMERS
        value: "30"
      - name: ZBX_STARTESCALATORS
        value: "30"
      - name: ZBX_STARTALERTERS
        value: "30"
      - name: ZBX_TIMEOUT
        value: "30"
      - name: ZBX_LOGSLOWQUERIES
        value: "3000"
      - name: ZBX_STARTDBSYNCERS
        value: "16"
      - name: ZBX_HOUSEKEEPINGFREQUENCY
        value: "1"
      - name: ZBX_MAXHOUSEKEEPERDELETE
        value: "50000"
      - name: ZBX_NODEADDRESS
        value: "{{ zbx_node_ip }}"
      - name: ZBX_HANODENAME
        value: "{{ zbx_node_name }}"
      - name: ZBX_SERVER_NAME
        value: "{{ zbx_server_name }}"
      - name: PHP_TZ
        value: "Europe/Amsterdam"
      - name: ZBX_SSO_IDP_CERT
        value: "/certs/Azure.cer"
      - name: ZBX_SSO_SETTINGS
        value: >-
          '{"baseurl": "https://{{ zbx_node_name }}", "use_proxy_headers": true, "security": {"requestedAuthnContext": false}}'

    stack_name: "zabbix-server"
    stack_compose_file: "/stacks/zabbix-server/docker-compose.yml"

  tasks:
    - import_tasks: ./common.yml